<?php
/**
 * @file
 * Drupal hooks
 */

/**
 * Implements hook_search_api_alter_callback_info().
 */
function search_api_attachments_paragraphs_search_api_alter_callback_info() {
  $callbacks['search_api_attachments_paragraphs_alter_settings'] = array(
    'name' => t('File attachments Paragraphs'),
    'description' => t('Extract the content of attached files of a referenced Paragraph and index it.'),
    'class' => 'SearchApiAttachmentsParagraphsAlterSettings',
  );
  return $callbacks;
}
