<?php
/**
 * @file
 * Drupal hooks
 */

/**
 * Implements hook_search_api_alter_callback_info().
 */
function search_api_attachments_multifield_search_api_alter_callback_info() {
  $callbacks['search_api_attachments_multifield_alter_settings'] = array(
    'name' => t('File attachments Multifield'),
    'description' => t('Extract the content of attached files of a multifield item and index it.'),
    'class' => 'SearchApiAttachmentsMultifieldAlterSettings',
  );
  return $callbacks;
}
