<?php
// Copyright 2005-2008 Khalid Baheyeldin http://2bits.com

// Variables
define('USERPOINTS_ROLE',               'userpoints_role_');
define('USERPOINTS_ROLE_TEXT_JOIN',     'userpoints_role_text_join');
define('USERPOINTS_ROLE_TEXT_LEAVE',    'userpoints_role_text_leave');
define('USERPOINTS_ROLE_SUBJECT_JOIN',  'userpoints_role_subject_join');
define('USERPOINTS_ROLE_SUBJECT_LEAVE', 'userpoints_role_subject_leave');

function userpoints_role_defaults($key) {
  $data = array(
    'join_subject' => 'Congratulations! You have joined a new role',

    'join_text'    => "!username,\n\nCongratulations!\nYou have met the minimum required points for joining a new role.\n\nAs a new member of this role, you now join a select few in having access to more areas and privileges on the web site.\n\nRole: !rolename\nPoints Required: !points\n\nWe extend our warmest welcome.",

    'leave_subject' => 'Sorry! You have left a role',

    'leave_text'    => "!username,\n\nWe are sorry!\nYou have lost the number of points required to stay in your current role.\n\nYou no longer have access to the areas and privileges of the following role:\n\nRole: !rolename\nPoints Required: !points.",
  );

  return $data[$key];
}

function userpoints_role_help($path, $arg) {
  switch ($path) {
    case 'admin/modules#description':
      return t('Users gain/lose roles as they earn !points', userpoints_translation());
  }
}

function userpoints_role_menu() {
  $items = array();

  $items['admin/config/people/userpoints/role/%'] = array(
    'title'            => '!Points roles settings',
    'title arguments'  => userpoints_translation(),
    'description'      => 'Settings for role',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('userpoints_role_admin_settings', 5),
    'access arguments' => array('administer userpoints'),
    'type'             => MENU_NORMAL_ITEM,
  );

  return $items;
}

function userpoints_role_admin_settings($form, $form_state, $rid) {
  $role_list = user_roles();
  $role_name = $role_list[$rid];

  $group = 'role';
  $form[$group] = array(
    '#type'        => 'fieldset',
    '#title'       => t('Role email settings for @role', array('@role' => $role_name)),
    '#description' => t('Role settings, subject and text of email.'),
    '#collapsible' => TRUE,
    '#collapsed'   => FALSE,
  );

  $form[$group][USERPOINTS_ROLE_SUBJECT_JOIN . $rid] = array(
    '#type'          => 'textfield',
    '#title'         => t('Subject of email to sent upon joining a role'),
    '#default_value' => variable_get(USERPOINTS_ROLE_SUBJECT_JOIN . $rid, t(userpoints_role_defaults('join_subject'))),
  );

  $form[$group][USERPOINTS_ROLE_TEXT_JOIN . $rid] = array(
    '#type'          => 'textarea',
    '#title'         => t('Text of email to sent upon joining a role'),
    '#default_value' => variable_get(USERPOINTS_ROLE_TEXT_JOIN . $rid, t(userpoints_role_defaults('join_text'))),
    '#width'         => 70,
    '#lines'         => 5,
  );

  $form[$group][USERPOINTS_ROLE_SUBJECT_LEAVE . $rid] = array(
    '#type'          => 'textfield',
    '#title'         => t('Subject of email to sent upon leaving a role'),
    '#default_value' => variable_get(USERPOINTS_ROLE_SUBJECT_LEAVE . $rid, t(userpoints_role_defaults('leave_subject'))),
  );

  $form[$group][USERPOINTS_ROLE_TEXT_LEAVE . $rid] = array(
    '#type'          => 'textarea',
    '#title'         => t('Text of email to sent upon leaving a role'),
    '#default_value' => variable_get(USERPOINTS_ROLE_TEXT_LEAVE . $rid, t(userpoints_role_defaults('leave_text'))),
    '#width'         => 70,
    '#lines'         => 5,
  );

  return system_settings_form($form);
}

/**
 * Role promotion/demotion based on points gained/lost
 */
function userpoints_role_userpoints($op, $params = array()) {
  switch($op) {
    case 'setting':
      $group = 'default_email';

      $form[$group] = array(
        '#type'        => 'fieldset',
        '#title'       => t('Roles email settings', userpoints_translation()),
        '#description' => t('Email subject and body for joining and leaving roles. You can modify that further for each role if you wish, using the links below each role. If you a role does not have its own subject and body settings, then the ones below will apply.'),
        '#collapsible' => TRUE,
        '#collapsed'   => TRUE,
        '#group'       => 'settings_additional',
        '#weight'      => 40,
      );

      $form[$group][USERPOINTS_ROLE_SUBJECT_JOIN] = array(
        '#type'          => 'textfield',
        '#title'         => t('Subject of email to sent upon joining a role'),
        '#default_value' => variable_get(USERPOINTS_ROLE_SUBJECT_JOIN, t(userpoints_role_defaults('join_subject'))),
      );

      $form[$group][USERPOINTS_ROLE_TEXT_JOIN] = array(
        '#type'          => 'textarea',
        '#title'         => t('Text of email to sent upon joining a role'),
        '#default_value' => variable_get(USERPOINTS_ROLE_TEXT_JOIN, t(userpoints_role_defaults('join_text'))),
        '#width'         => 70,
        '#lines'         => 5,
        );

      $form[$group][USERPOINTS_ROLE_SUBJECT_LEAVE] = array(
        '#type'          => 'textfield',
        '#title'         => t('Subject of email to sent upon leaving a role'),
        '#default_value' => variable_get(USERPOINTS_ROLE_SUBJECT_LEAVE, t(userpoints_role_defaults('leave_subject'))),
      );

      $form[$group][USERPOINTS_ROLE_TEXT_LEAVE] = array(
        '#type'          => 'textarea',
        '#title'         => t('Text of email to sent upon leaving a role'),
        '#default_value' => variable_get(USERPOINTS_ROLE_TEXT_LEAVE, t(userpoints_role_defaults('leave_text'))),
        '#width'         => 70,
        '#lines'         => 5,
        );

      $role_list = userpoints_role_load_role_points(TRUE);

      $group = 'roles';

      $form[$group] = array(
        '#type'        => 'fieldset',
        '#title'       => t('Role changes', userpoints_translation()),
        '#description' => t('Users join/leave to roles as they gain/lose points. Points required to join each role. Enter 0 to ignore that role.'),
        '#collapsible' => TRUE,
        '#collapsed'   => TRUE,
        '#group'       => 'settings_additional',
        '#weight'      => 35,
      );

      if (empty($role_list)) {
        $form[$group]['no_roles'] = array(
          '#type '  => 'item',
          '#prefix' => '<div>',
          '#suffix' => '</div>',
          '#value'  => t('There are no additional roles defined. This module will not work for anonymous and authenticated users. You need to define more roles to use this module.'),
        );
      }

      foreach($role_list as $role_point) {
        $name = $role_point['name'];
        $rid  = $role_point['rid'];
        $role = USERPOINTS_ROLE . $rid;

        $form[$group][$role] = array(
          '#type'          => 'textfield',
          '#title'         => t('Points for role %role', array('%role' => $name)),
          '#default_value' => variable_get($role, 0),
        );
        $form[$group][$role .'_tid'] = array(
          '#type'          => 'select',
          '#title'         => t('Category'),
          '#default_value' => variable_get($role .'_tid', 0),
          '#options'       => userpoints_get_categories(),
          '#description'   => t('Category of these points'),
        );
        $form[$group][$role . 'links'] = array(
          '#type '  => 'item',
          '#prefix' => '<div>',
          '#suffix' => '</div>',
          '#markup'  => t('Change email settings for !role', array('!role' => l($name, 'admin/config/people/userpoints/role/' . $rid, array('html' => TRUE)))),
        );
      }

      return $form;
      break;

    case 'points after':
      // Check the roles the user belong to, and if they are exempted from userpoints
      _userpoints_role_update_roles($params);
      break;
  }
}

/**
 * Check if the user needs to be added or removed from roles.
 *
 * @param array $params
 *   Userpoints transaction.
 */
function _userpoints_role_update_roles($transaction) {
  $points = userpoints_get_current_points($transaction['uid'], $transaction['tid']);

  $role_points = userpoints_role_load_role_points();
  if ($transaction['points'] < 0) {
    // Negative transaction point amount, we may need to remove the user for
    // certain roles.
    foreach($role_points as $role_point) {
      // Only continue if the role has points assigned and the category
      // equals the category of the points transaction.
      if ($role_point['points'] > 0 && $role_point['tid'] == $transaction['tid']) {
        if ($points < $role_point['points']) {
          // Remove user from role if he has not enough points.
          userpoints_role_leave($transaction['uid'], $role_point);
        }
      }
    }
  }
  else {
    // Positive transaction point amount, check if user needs to have roles
    // assigned.
    foreach($role_points as $role_point) {
      // Only continue if the role has points assigned and the category
      // equals the category of the points transaction.
      if ($role_point['points'] > 0 && $role_point['tid'] == $transaction['tid']) {
        if ($points >= $role_point['points']) {
          // Assign the role to the user.
          userpoints_role_join($transaction['uid'], $role_point);
        }
      }
    }
  }
}

/**
 * Check if user is in a certain role.
 *
 * @param int $uid
 *   User ID.
 * @param int $rid
 *   Role ID.
 *
 * @return boolean
 *   TRUE if the user has the given role, FALSE if not.
 */
function userpoints_role_check_user_role($uid, $rid) {
  return (bool)db_query_range("SELECT 1 FROM {users_roles} WHERE rid = :rid AND uid = :uid", 0, 1, array(':uid' => $uid, ':rid' => $rid))->fetchField();;
}

function userpoints_role_join($uid, $role_point) {
  $rid = $role_point['rid'];
  $points = $role_point['points'];
  if (userpoints_role_check_user_role($uid, $rid)) {
    // User already has that role, no need to do anything
  }
  else {
    userpoints_role_send_mail('join', $uid, $role_point);
    user_multiple_role_edit(array($uid), 'add_role', $rid);
  }
}

function userpoints_role_leave($uid, $role_point) {
  $rid = $role_point['rid'];
  $points = $role_point['points'];
  if (userpoints_role_check_user_role($uid, $rid)) {
    // User is in that role, need to remove him
    userpoints_role_send_mail('leave', $uid, $role_point);
    user_multiple_role_edit(array($uid), 'remove_role', $rid);
  }
}

function userpoints_role_send_mail($op, $uid, $role_point) {
  global $language;

  $account = user_load($uid);
  $vars = array(
    '!username' => $account->name,
    '!rolename' => $role_point['name'],
    '!points'   => $role_point['points'],
    );

  $params = array(
    'subject' => userpoints_role_email($op, 'subject', $role_point['rid'], $vars),
    'body'    => userpoints_role_email($op, 'text',    $role_point['rid'], $vars),
  );

  $from = variable_get('site_mail', ini_get('sendmail_from'));
  drupal_mail('userpoints_role', 'userpoints_role', $account->mail, $language, $params, $from);
}

function userpoints_role_email($op, $type, $rid, $vars) {
  // Note: this function manipulates variable names, so be careful changing any of them


  // Get the data for this role
  $output = variable_get('userpoints_role_' . $type . '_' . $op . $rid, '');
  if (!$output) {
    // If it is empty, use the default data
    $output = variable_get('userpoints_role_' . $type . '_' . $op, userpoints_role_defaults($op . '_' . $type));
  }
  // Substitute the variables
  return t($output, $vars);
}

/**
 * Implements hook_mail().
 */
function userpoints_role_mail($key, &$message, $params) {
  $message['subject'] = $params['subject'];
  $message['body'][] = drupal_html_to_text($params['body']);
}

function userpoints_role_load_role_points($list_all = FALSE) {
  $role_points = array();
  foreach (user_roles() as $rid => $name) {
    if (1 == $rid || 2 == $rid) {
      // Anonymous and authenticated roles are ignored
      continue;
    }

    if (!$list_all) {
      $points = variable_get(USERPOINTS_ROLE . $rid, 0);
      if ($points) {
        // In case the site admin did not enter any points for a role, we ignore it
        $role_points[] = _userpoints_role_load_role_data($rid, $name);
      }
    }
    else {
      // Include the role regardless
      $role_points[] = _userpoints_role_load_role_data($rid, $name);
    }
  }
  return $role_points;
}

function _userpoints_role_load_role_data($rid, $name) {
  return array(
    'rid'    => $rid,
    'name'   => $name,
    'points' => (int)variable_get(USERPOINTS_ROLE . $rid, 0),
    'tid'    => (int)variable_get(USERPOINTS_ROLE . $rid .'_tid', 0),
  );
}
