<?php
/**
 * @file
 * Drupal hooks
 */

/**
 * Implements hook_search_api_alter_callback_info().
 */
function search_api_attachments_commerce_product_reference_search_api_alter_callback_info() {
  $callbacks['search_api_attachments_commerce_product_reference_alter_settings'] = array(
    'name' => t('File attachments Commerce product reference'),
    'description' => t('Extract the content of attached files of a referenced Commerce product and index it.'),
    'class' => 'SearchApiAttachmentsCommerceProductReferenceAlterSettings',
  );
  return $callbacks;
}
